/**
 * author: akajontsai-devel AT yahoo DOT com, 2012
 * file: calendar_settings_default.js
 *
 * DO NOT EDIT THIS FILE
 *
 */

var DEFAULTS = {
    'TIME_HOUR_ONLY': false,
    'TIME_24_HOUR': true
};
